### ISSUE TITLE
make each element in the list clickable and long pressable

### ISSUE THREAD

**Issue by sirvon** [edekhayser/Timeline#15]
Is it already built in the lib to click on the elements or do I need to customize this ability?

thx for this lib!

**Comment by edekhayser** [comment]
Tapping elements is only supported for images. If you want to customize the timeline so that this is possible, you can probably go into the class itself and add a UITapGestureRecognizer to the individual subviews. This might require some changes to the TimeFrame struct, and the gestures can be added in the `setupContent()` method.

**Comment by sirvon** [comment]
ty
